import React, { useState } from "react"

import { Loader, Card, FormField } from "../components"

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />)
  }

  return (
    <h2 className="mt-5 text-xl font-bold uppercase text-not-that-black">
      {title}
    </h2>
  )
}

const Home = () => {
  const [loading, setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState(null)
  const [searcthText, setSearchText] = useState("aa")

  return (
    <section className="mx-auto max-w-7xl">
      <div className="text-[32px] font-bold text-not-that-black">
        <h1>The Community Showcase</h1>
        <p className="mt-2 max-w-[500px] text-[14px] text-sky-blue">
          Browse through a collection of imaginative and visually stunning
          images generated by{" "}
          <span className="font-extrabold text-not-that-black">DALL-E AI</span>
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex items-center justify-center">
            <Loader />
          </div>
        ) : (
          <>
            {searcthText && (
              <h2 className="mb-3 text-xl font-medium text-smoke-gray">
                Showing results for
                <span className="text-not-that-black"> {searcthText}</span>
              </h2>
            )}

            <div className="grid grid-cols-1 gap-3 xs:grid-cols-2 sm:grid-cols-3 lg:grid-cols-4">
              {searcthText ? (
                <RenderCards data={[]} title="No search results found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Home
